# Copyright 2025 TIER IV, inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Naming utilities for the autoware architecture system."""

import re


def pascal_to_snake(name: str) -> str:
    """Convert PascalCase to snake_case.
    
    Args:
        name: String in PascalCase format
        
    Returns:
        String in snake_case format
    """
    if not name:
        return ""
    
    # Insert underscore before uppercase letters that follow lowercase letters
    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    # Insert underscore before uppercase letters that follow lowercase letters or digits
    return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()

def snake_to_pascal(name: str) -> str:
    """Convert snake_case to PascalCase.
    
    Args:
        name: String in snake_case format
        
    Returns:
        String in PascalCase format
    """
    if not name:
        return ""
    
    components = name.split('_')
    return ''.join(word.capitalize() for word in components)

def generate_unique_id(namespace: list[str], *components: str) -> str:
    """Generate a unique identifier string from a namespace and optional suffix components.

    The unique id is generated by hashing the structural representation of the arguments.
    This ensures that the distinction between the namespace list and additional components
    is preserved (e.g., ([a, b], c) != ([a], b, c)).

    Args:
        namespace: Ordered list of namespace segments.
        *components: Optional additional name parts.

    Returns:
        A unique identifier string (UUID) stable across executions.
    """
    # Using repr() captures the structure (list vs tuple items) and content.
    key = f"{namespace!r}::{components!r}"
    import uuid
    return str(uuid.uuid5(uuid.NAMESPACE_DNS, key))
